//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUnitSample
{

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public class Specification : global::System.Configuration.ApplicationSettingsBase
    {

        public static Specification defaultInstance = ((Specification)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Specification())));

        public static Specification Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("menuLIProductManagement0")]
        public string ProductMenu_ID
        {
            get
            {
                return ((string)(this["ProductMenu_ID"]));
            }
            set
            {
                this["ProductMenu_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subMenuLiSpecifications0")]
        public string SpecificationMenu_ID
        {
            get
            {
                return ((string)(this["SpecificationMenu_ID"]));
            }
            set
            {
                this["SpecificationMenu_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("createNew")]
        public string CreateNew
        {
            get
            {
                return ((string)(this["CreateNew"]));
            }
            set
            {
                this["CreateNew"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("productLinkDisplay")]
        public string spec_number_ID
        {
            get
            {
                return ((string)(this["spec_number_ID"]));
            }
            set
            {
                this["spec_number_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bill-to-customer")]
        public string customer_ID
        {
            get
            {
                return ((string)(this["customer_ID"]));
            }
            set
            {
                this["customer_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpecID")]
        public string specID_ID
        {
            get
            {
                return ((string)(this["specID_ID"]));
            }
            set
            {
                this["specID_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("productstyle")]
        public string productstyle_ID
        {
            get
            {
                return ((string)(this["productstyle_ID"]));
            }
            set
            {
                this["productstyle_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#divExternalCode > #product-external-code")]
        public string productGL_CSS
        {
            get
            {
                return ((string)(this["productGL_CSS"]));
            }
            set
            {
                this["productGL_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("material-grade-link-field")]
        public string materialGrade_ID
        {
            get
            {
                return ((string)(this["materialGrade_ID"]));
            }
            set
            {
                this["materialGrade_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ddlProductBoardSupplier")]
        public string Spec_supplier_ID
        {
            get
            {
                return ((string)(this["Spec_supplier_ID"]));
            }
            set
            {
                this["Spec_supplier_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FL")]
        public string lenght_ID
        {
            get
            {
                return ((string)(this["lenght_ID"]));
            }
            set
            {
                this["lenght_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FW")]
        public string Width_ID
        {
            get
            {
                return ((string)(this["Width_ID"]));
            }
            set
            {
                this["Width_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FD")]
        public string Depth_ID
        {
            get
            {
                return ((string)(this["Depth_ID"]));
            }
            set
            {
                this["Depth_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReCalculate")]
        public string Recalculate_ID
        {
            get
            {
                return ((string)(this["Recalculate_ID"]));
            }
            set
            {
                this["Recalculate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("autoEditBox")]
        public string MaterialandOperationAddOn_ID
        {
            get
            {
                return ((string)(this["MaterialandOperationAddOn_ID"]));
            }
            set
            {
                this["MaterialandOperationAddOn_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"bill-to-customer-container\"]/div/div/ul/li/a")]
        public string CutomerDropdwon_XPATH
        {
            get
            {
                return ((string)(this["CutomerDropdwon_XPATH"]));
            }
            set
            {
                this["CutomerDropdwon_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"divProductStyleSelector\"]/div/ul/li/a")]
        public string ProductStyleDropdown_ID
        {
            get
            {
                return ((string)(this["ProductStyleDropdown_ID"]));
            }
            set
            {
                this["ProductStyleDropdown_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"divExternalCode\"]/div/ul/li/a")]
        public string GL_code_IDDropdown_XPATH
        {
            get
            {
                return ((string)(this["GL_code_IDDropdown_XPATH"]));
            }
            set
            {
                this["GL_code_IDDropdown_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#divBoard > div.custom-autocomplite-field.not-full-width > div.ui-autocomplete-pa" +
            "gination-results > ul.ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-conte" +
            "nt.ui-corner-all > li.ui-menu-item > a.ui-corner-all")]
        public string Material_grade_dropdown_XPATH
        {
            get
            {
                return ((string)(this["Material_grade_dropdown_XPATH"]));
            }
            set
            {
                this["Material_grade_dropdown_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("validateButton")]
        public string validate_Save_Button_ID
        {
            get
            {
                return ((string)(this["validate_Save_Button_ID"]));
            }
            set
            {
                this["validate_Save_Button_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#div-buttons > #show-estimates")]
        public string Bussiness_Spec_CSS
        {
            get
            {
                return ((string)(this["Bussiness_Spec_CSS"]));
            }
            set
            {
                this["Bussiness_Spec_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("create-new-business-spec")]
        public string New_Buss_Spec_ID
        {
            get
            {
                return ((string)(this["New_Buss_Spec_ID"]));
            }
            set
            {
                this["New_Buss_Spec_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"productOperation\"]/tbody/tr[2]/td[4]")]
        public string Operation_grid_XPATH
        {
            get
            {
                return ((string)(this["Operation_grid_XPATH"]));
            }
            set
            {
                this["Operation_grid_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.control-group > #div-buttons > #check-routing")]
        public string CheckRoutings_CSS
        {
            get
            {
                return ((string)(this["CheckRoutings_CSS"]));
            }
            set
            {
                this["CheckRoutings_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("route-list")]
        public string RoutingList_ID
        {
            get
            {
                return ((string)(this["RoutingList_ID"]));
            }
            set
            {
                this["RoutingList_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("modalTestRouting")]
        public string RouteCLose_ID
        {
            get
            {
                return ((string)(this["RouteCLose_ID"]));
            }
            set
            {
                this["RouteCLose_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save-without-validation")]
        public string Save_ProductEstimate_ID
        {
            get
            {
                return ((string)(this["Save_ProductEstimate_ID"]));
            }
            set
            {
                this["Save_ProductEstimate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("divProdDataForEstimateTool")]
        public string ProductDataestimate_ID
        {
            get
            {
                return ((string)(this["ProductDataestimate_ID"]));
            }
            set
            {
                this["ProductDataestimate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("estimates-content-container")]
        public string EstimateList_ID
        {
            get
            {
                return ((string)(this["EstimateList_ID"]));
            }
            set
            {
                this["EstimateList_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("create-estimate")]
        public string CreateEstimate_ID
        {
            get
            {
                return ((string)(this["CreateEstimate_ID"]));
            }
            set
            {
                this["CreateEstimate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("costModel")]
        public string CostModel_ID
        {
            get
            {
                return ((string)(this["CostModel_ID"]));
            }
            set
            {
                this["CostModel_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quantity")]
        public string Qauntity_ID
        {
            get
            {
                return ((string)(this["Qauntity_ID"]));
            }
            set
            {
                this["Qauntity_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("get-routes-for-estimate")]
        public string SaveAndGenerateRoutes_ID
        {
            get
            {
                return ((string)(this["SaveAndGenerateRoutes_ID"]));
            }
            set
            {
                this["SaveAndGenerateRoutes_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("routes-grids")]
        public string RoutesGenrated_ID
        {
            get
            {
                return ((string)(this["RoutesGenrated_ID"]));
            }
            set
            {
                this["RoutesGenrated_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select-unitizing-type-button")]
        public string SelectUnitization_ID
        {
            get
            {
                return ((string)(this["SelectUnitization_ID"]));
            }
            set
            {
                this["SelectUnitization_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"unitizing-types\"]/tbody")]
        public string UnitizationTable_XPATH
        {
            get
            {
                return ((string)(this["UnitizationTable_XPATH"]));
            }
            set
            {
                this["UnitizationTable_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.custom-autocomplite-field > div.ui-autocomplete-pagination-results > ul.ui-au" +
            "tocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.ui-corner-all > li.ui-me" +
            "nu-item > a.ui-corner-all")]
        public string costmodeldropdown_CSS
        {
            get
            {
                return ((string)(this["costmodeldropdown_CSS"]));
            }
            set
            {
                this["costmodeldropdown_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("all-unitizing-types-modal")]
        public string UnitizationGrid_ID
        {
            get
            {
                return ((string)(this["UnitizationGrid_ID"]));
            }
            set
            {
                this["UnitizationGrid_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#pEstimateRoute > input.btn.devide-button")]
        public string Split_CSS
        {
            get
            {
                return ((string)(this["Split_CSS"]));
            }
            set
            {
                this["Split_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("get-pricing")]
        public string CreateEstimatePrice_ID
        {
            get
            {
                return ((string)(this["CreateEstimatePrice_ID"]));
            }
            set
            {
                this["CreateEstimatePrice_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("calculate-prices")]
        public string Calculate_Price_ID
        {
            get
            {
                return ((string)(this["Calculate_Price_ID"]));
            }
            set
            {
                this["Calculate_Price_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gview_estimate-price-table")]
        public string EstimatePriceList_ID
        {
            get
            {
                return ((string)(this["EstimatePriceList_ID"]));
            }
            set
            {
                this["EstimatePriceList_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save-prices")]
        public string SavePriceList_ID
        {
            get
            {
                return ((string)(this["SavePriceList_ID"]));
            }
            set
            {
                this["SavePriceList_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save-prices-and-approve")]
        public string ApprovePriceList_ID
        {
            get
            {
                return ((string)(this["ApprovePriceList_ID"]));
            }
            set
            {
                this["ApprovePriceList_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"price-saved-message\"]/div/div/div[3]/button")]
        public string SaveAlert_XPATH
        {
            get
            {
                return ((string)(this["SaveAlert_XPATH"]));
            }
            set
            {
                this["SaveAlert_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("all-unitizing-types-modal")]
        public string UnitizationModel_ID
        {
            get
            {
                return ((string)(this["UnitizationModel_ID"]));
            }
            set
            {
                this["UnitizationModel_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("autoEditBox")]
        public string AddMatrial_ID
        {
            get
            {
                return ((string)(this["AddMatrial_ID"]));
            }
            set
            {
                this["AddMatrial_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ul.ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.ui-corner-all > l" +
            "i.ui-menu-item > a.ui-corner-all")]
        public string AddMatrialDropdown_CSS
        {
            get
            {
                return ((string)(this["AddMatrialDropdown_CSS"]));
            }
            set
            {
                this["AddMatrialDropdown_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"productOperation\"]/tbody")]
        public string AllOperation_grid_XPATH
        {
            get
            {
                return ((string)(this["AllOperation_grid_XPATH"]));
            }
            set
            {
                this["AllOperation_grid_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"pProductOperation_left\"]/table/tbody/tr/td[1]")]
        public string Operation_Delete_XPATH
        {
            get
            {
                return ((string)(this["Operation_Delete_XPATH"]));
            }
            set
            {
                this["Operation_Delete_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sData")]
        public string Suppliersubmit_ID
        {
            get
            {
                return ((string)(this["Suppliersubmit_ID"]));
            }
            set
            {
                this["Suppliersubmit_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"prodDataForEstimateMaterial\"]/tbody/tr[2]")]
        public string MaterialAddon_XPATH
        {
            get
            {
                return ((string)(this["MaterialAddon_XPATH"]));
            }
            set
            {
                this["MaterialAddon_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui-datepicker-div")]
        public string Datpicker_ID
        {
            get
            {
                return ((string)(this["Datpicker_ID"]));
            }
            set
            {
                this["Datpicker_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("save-without-validation")]
        public string SaveProdEstimate_ID
        {
            get
            {
                return ((string)(this["SaveProdEstimate_ID"]));
            }
            set
            {
                this["SaveProdEstimate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("divProdDataForEstimateMaterial")]
        public string MaterialAddonInSpec_ID
        {
            get
            {
                return ((string)(this["MaterialAddonInSpec_ID"]));
            }
            set
            {
                this["MaterialAddonInSpec_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#editmodproductOperation > div#editcntproductOperation > div > form#FrmGrid_pr" +
            "oductOperation > table#TblGrid_productOperation > tbody > tr#tr_ToolLinkText > t" +
            "d.DataTD > input#ToolLinkText")]
        public string ToolLink_CSS
        {
            get
            {
                return ((string)(this["ToolLink_CSS"]));
            }
            set
            {
                this["ToolLink_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OperationProperties.NumberOfColors")]
        public string NUmberOfColour_ID
        {
            get
            {
                return ((string)(this["NUmberOfColour_ID"]));
            }
            set
            {
                this["NUmberOfColour_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#editcntproductOperation > div > table#TblGrid_productOperation_2 > tbody > tr" +
            "#Act_Buttons > td.EditButton > a#sData")]
        public string SubmitTool_CSS
        {
            get
            {
                return ((string)(this["SubmitTool_CSS"]));
            }
            set
            {
                this["SubmitTool_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"div#editmodproductOperation > div#editcntproductOperation > div > form#FrmGrid_productOperation > table#TblGrid_productOperation > tbody > tr#tr_ToolLinkText > td.DataTD > div.ui-autocomplete-pagination-results > ul.ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.ui-corner-all> li.ui-menu-item > a.ui-corner-all")]
        public string ToolLinkDropdown_CSS
        {
            get
            {
                return ((string)(this["ToolLinkDropdown_CSS"]));
            }
            set
            {
                this["ToolLinkDropdown_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"productMaterial\"]/tbody")]
        public string AllMaterial_grid_XPATH
        {
            get
            {
                return ((string)(this["AllMaterial_grid_XPATH"]));
            }
            set
            {
                this["AllMaterial_grid_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialProperties.PercentCoverage")]
        public string ColourPercentage_ID
        {
            get
            {
                return ((string)(this["ColourPercentage_ID"]));
            }
            set
            {
                this["ColourPercentage_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialProperties.NumberOfCostUnitWasted")]
        public string ColourUnitsWasted_ID
        {
            get
            {
                return ((string)(this["ColourUnitsWasted_ID"]));
            }
            set
            {
                this["ColourUnitsWasted_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("table#TblGrid_productMaterial_2 > tbody > tr#Act_Buttons > td.EditButton > a#sDat" +
            "a")]
        public string ColourPercentageSubmit_CSS
        {
            get
            {
                return ((string)(this["ColourPercentageSubmit_CSS"]));
            }
            set
            {
                this["ColourPercentageSubmit_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//form[@action=\"/CBSnew/ProductDataForEstimate/Edit\"]")]
        public string ProductEstimateInformation_XPATH
        {
            get
            {
                return ((string)(this["ProductEstimateInformation_XPATH"]));
            }
            set
            {
                this["ProductEstimateInformation_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#editmodproductOperation > div#editcntproductOperation > div > form#FrmGrid_pr" +
            "oductOperation > table#TblGrid_productOperation > tbody > tr#tr_ToolLinkText > t" +
            "d.DataTD > input#ToolLinkText")]
        public string DiecutToolid_CSS
        {
            get
            {
                return ((string)(this["DiecutToolid_CSS"]));
            }
            set
            {
                this["DiecutToolid_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"div#editmodproductOperation > div#editcntproductOperation > div > form#FrmGrid_productOperation > table#TblGrid_productOperation > tbody > tr#tr_ToolLinkText > td.DataTD > input#ToolLinkText > div.ui-autocomplete-pagination-results > ul:nth-child(1) > li:nth-child(2) > a")]
        public string ToolIDdropdown_CSS
        {
            get
            {
                return ((string)(this["ToolIDdropdown_CSS"]));
            }
            set
            {
                this["ToolIDdropdown_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#editmodproductOperation > div#editcntproductOperation > div > form#FrmGrid_pr" +
            "oductOperation > table#TblGrid_productOperation > tbody > tr#tr_OperationPropert" +
            "ies.NumberUp > td.DataTD > input#OperationProperties.NumberUp")]
        public string DieCutNumberUP_CSS
        {
            get
            {
                return ((string)(this["DieCutNumberUP_CSS"]));
            }
            set
            {
                this["DieCutNumberUP_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#editmodproductOperation > div#editcntproductOperation > div > form#FrmGrid_pr" +
            "oductOperation > table#TblGrid_productOperation > tbody > tr#tr_OperationPropert" +
            "ies.NumberOut > td.DataTD > input#OperationProperties.NumberOut")]
        public string DieCutNumberOUT_CSS
        {
            get
            {
                return ((string)(this["DieCutNumberOUT_CSS"]));
            }
            set
            {
                this["DieCutNumberOUT_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//ul[@class=\'ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-cor" +
            "ner-all\'])[9]/li[1]/a")]
        public string Bundlestarpping_CSS
        {
            get
            {
                return ((string)(this["Bundlestarpping_CSS"]));
            }
            set
            {
                this["Bundlestarpping_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"prodDataForEstimateMaterial\"]/tbody/tr[2]")]
        public string StrappingprodData_ID
        {
            get
            {
                return ((string)(this["StrappingprodData_ID"]));
            }
            set
            {
                this["StrappingprodData_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cost")]
        public string StappingCost_ID
        {
            get
            {
                return ((string)(this["StappingCost_ID"]));
            }
            set
            {
                this["StappingCost_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostStartDate")]
        public string CostStartDate_ID
        {
            get
            {
                return ((string)(this["CostStartDate_ID"]));
            }
            set
            {
                this["CostStartDate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("table#TblGrid_prodDataForEstimateMaterial_2 > tbody > tr#Act_Buttons > td.EditBut" +
            "ton > a#sData")]
        public string CostSubmit_CSS
        {
            get
            {
                return ((string)(this["CostSubmit_CSS"]));
            }
            set
            {
                this["CostSubmit_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("divProdDataForEstimateMaterial")]
        public string ProductDataforEstimateMat_ID
        {
            get
            {
                return ((string)(this["ProductDataforEstimateMat_ID"]));
            }
            set
            {
                this["ProductDataforEstimateMat_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#pricing-screen > div.row-fluid > div#estimate-price > div#estimate-pricing > " +
            "fieldset > div > div > select")]
        public string PricingType_CSS
        {
            get
            {
                return ((string)(this["PricingType_CSS"]));
            }
            set
            {
                this["PricingType_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("form-validation-field-0")]
        public string PricingMetricvalue_ID
        {
            get
            {
                return ((string)(this["PricingMetricvalue_ID"]));
            }
            set
            {
                this["PricingMetricvalue_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add-qty")]
        public string addqty_ID
        {
            get
            {
                return ((string)(this["addqty_ID"]));
            }
            set
            {
                this["addqty_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"prices-and-quantities\"]/tbody")]
        public string FromToTable_XPATH
        {
            get
            {
                return ((string)(this["FromToTable_XPATH"]));
            }
            set
            {
                this["FromToTable_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("business-discount-link")]
        public string businesdiscount_ID
        {
            get
            {
                return ((string)(this["businesdiscount_ID"]));
            }
            set
            {
                this["businesdiscount_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gview_estimate-price-table")]
        public string estimatepricetable_ID
        {
            get
            {
                return ((string)(this["estimatepricetable_ID"]));
            }
            set
            {
                this["estimatepricetable_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#gview_estimate-price-table > div.ui-state-default.ui-jqgrid-hdiv > div.ui-jqg" +
            "rid-hbox > table.ui-jqgrid-htable > thead > tr.ui-jqgrid-labels.jqg-second-row-h" +
            "eader > th:nth-child(2) > a.grid-header-link")]
        public string CosttableValues_CSS
        {
            get
            {
                return ((string)(this["CosttableValues_CSS"]));
            }
            set
            {
                this["CosttableValues_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#gview_estimate-price-table > div.ui-state-default.ui-jqgrid-hdiv > div.ui-jqg" +
            "rid-hbox > table.ui-jqgrid-htable > thead > tr.ui-jqgrid-labels.jqg-second-row-h" +
            "eader > th:nth-child(3) > a.grid-header-link")]
        public string CosttableValues1_CSS
        {
            get
            {
                return ((string)(this["CosttableValues1_CSS"]));
            }
            set
            {
                this["CosttableValues1_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Factory Ticket")]
        public string FactoryTicket_ID
        {
            get
            {
                return ((string)(this["FactoryTicket_ID"]));
            }
            set
            {
                this["FactoryTicket_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Estimate Cost")]
        public string EstimateCost_LINK
        {
            get
            {
                return ((string)(this["EstimateCost_LINK"]));
            }
            set
            {
                this["EstimateCost_LINK"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("set-as-Manufacturable")]
        public string setasManufacturable_ID
        {
            get
            {
                return ((string)(this["setasManufacturable_ID"]));
            }
            set
            {
                this["setasManufacturable_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list2\"]/tbody/tr[2]")]
        public string CostEstimate_XPATH
        {
            get
            {
                return ((string)(this["CostEstimate_XPATH"]));
            }
            set
            {
                this["CostEstimate_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list5\"]/tbody")]
        public string RouteList_XPATH
        {
            get
            {
                return ((string)(this["RouteList_XPATH"]));
            }
            set
            {
                this["RouteList_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list11\"]/tbody")]
        public string materialList_XPATH
        {
            get
            {
                return ((string)(this["materialList_XPATH"]));
            }
            set
            {
                this["materialList_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"list16\"]/tbody/tr[2]")]
        public string CostMaterialList_XPATH
        {
            get
            {
                return ((string)(this["CostMaterialList_XPATH"]));
            }
            set
            {
                this["CostMaterialList_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//ul[@class=\'ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-cor" +
            "ner-all\'])[8]/li[1]/a")]
        public string InkColourMaterial_XPATH
        {
            get
            {
                return ((string)(this["InkColourMaterial_XPATH"]));
            }
            set
            {
                this["InkColourMaterial_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialID")]
        public string ProdDataMaterialID_ID
        {
            get
            {
                return ((string)(this["ProdDataMaterialID_ID"]));
            }
            set
            {
                this["ProdDataMaterialID_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"prodDataForEstimateToolType\"]/tbody/tr[2]")]
        public string ProdDataToolType_ID
        {
            get
            {
                return ((string)(this["ProdDataToolType_ID"]));
            }
            set
            {
                this["ProdDataToolType_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"prodDataForEstimateToolType\"]/tbody/tr[2]/td[2]")]
        public string ProdDataToolName_ID
        {
            get
            {
                return ((string)(this["ProdDataToolName_ID"]));
            }
            set
            {
                this["ProdDataToolName_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolID")]
        public string ProdDataToolID_ID
        {
            get
            {
                return ((string)(this["ProdDataToolID_ID"]));
            }
            set
            {
                this["ProdDataToolID_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("table#TblGrid_prodDataForEstimateToolType > tbody > tr:nth-child(7) > td:nth-chil" +
            "d(2)  > input#Cost")]
        public string ProdDataToolCost_XPATH
        {
            get
            {
                return ((string)(this["ProdDataToolCost_XPATH"]));
            }
            set
            {
                this["ProdDataToolCost_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolPricingType")]
        public string ToolPricingType_ID
        {
            get
            {
                return ((string)(this["ToolPricingType_ID"]));
            }
            set
            {
                this["ToolPricingType_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("table#TblGrid_prodDataForEstimateToolType > tbody > tr#tr_ToolPricingType > td.Da" +
            "taTD > div.ui-autocomplete-pagination-results > ul.ui-autocomplete.ui-front.ui-m" +
            "enu.ui-widget.ui-widget-content.ui-corner-all > li.ui-menu-item > a.ui-corner-al" +
            "l")]
        public string ToolPricingTypeDropDown_ID
        {
            get
            {
                return ((string)(this["ToolPricingTypeDropDown_ID"]));
            }
            set
            {
                this["ToolPricingTypeDropDown_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("table#TblGrid_prodDataForEstimateToolType_2 > tbody > tr#Act_Buttons > td.EditBut" +
            "ton > a#sData")]
        public string ToolPricingTypeSubmit_ID
        {
            get
            {
                return ((string)(this["ToolPricingTypeSubmit_ID"]));
            }
            set
            {
                this["ToolPricingTypeSubmit_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"productMaterial\"]/tbody")]
        public string ProductMaterialInk_XPATH
        {
            get
            {
                return ((string)(this["ProductMaterialInk_XPATH"]));
            }
            set
            {
                this["ProductMaterialInk_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialProperties.PercentCoverage")]
        public string PercentCoverage_ID
        {
            get
            {
                return ((string)(this["PercentCoverage_ID"]));
            }
            set
            {
                this["PercentCoverage_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialProperties.NumberOfCostUnitWasted")]
        public string NumberOfCostUnitWasted_ID
        {
            get
            {
                return ((string)(this["NumberOfCostUnitWasted_ID"]));
            }
            set
            {
                this["NumberOfCostUnitWasted_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("table#TblGrid_productMaterial_2 > tbody > tr#Act_Buttons > td.EditButton > a#sDat" +
            "a")]
        public string SubmitCoverage_CSS
        {
            get
            {
                return ((string)(this["SubmitCoverage_CSS"]));
            }
            set
            {
                this["SubmitCoverage_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("warehouse")]
        public string warehouse_ID
        {
            get
            {
                return ((string)(this["warehouse_ID"]));
            }
            set
            {
                this["warehouse_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@class=\'ui-autocomplete-pagination-results\'])[4]/ul/li[1]/a")]
        public string WarehouseDropdown_XPATH
        {
            get
            {
                return ((string)(this["WarehouseDropdown_XPATH"]));
            }
            set
            {
                this["WarehouseDropdown_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShipToCustomer")]
        public string ShipToCustomer_ID
        {
            get
            {
                return ((string)(this["ShipToCustomer_ID"]));
            }
            set
            {
                this["ShipToCustomer_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shipmentMethod")]
        public string shipmentMethod_ID
        {
            get
            {
                return ((string)(this["shipmentMethod_ID"]));
            }
            set
            {
                this["shipmentMethod_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("busines-discount")]
        public string businesdiscountinspec_ID
        {
            get
            {
                return ((string)(this["businesdiscountinspec_ID"]));
            }
            set
            {
                this["businesdiscountinspec_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("createsameproduct-button")]
        public string createsameproduct_ID
        {
            get
            {
                return ((string)(this["createsameproduct_ID"]));
            }
            set
            {
                this["createsameproduct_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cancel-button")]
        public string AllBusinessSpec_ID
        {
            get
            {
                return ((string)(this["AllBusinessSpec_ID"]));
            }
            set
            {
                this["AllBusinessSpec_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"estimate\"]/tbody")]
        public string AllbusinesspsecApprove_XPATH
        {
            get
            {
                return ((string)(this["AllbusinesspsecApprove_XPATH"]));
            }
            set
            {
                this["AllbusinesspsecApprove_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("td.ui-widget-content.subgrid-data > div.tablediv > div.ui-jqgrid.ui-widget.ui-wid" +
            "get-content.ui-corner-all > div.ui-jqgrid-view > div.ui-jqgrid-bdiv > div > tabl" +
            "e.ui-jqgrid-btable > tbody > tr.ui-widget-content.jqgrow.ui-row-ltr > td:nth-chi" +
            "ld(10)")]
        public string allspectable_CSS
        {
            get
            {
                return ((string)(this["allspectable_CSS"]));
            }
            set
            {
                this["allspectable_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("copy-estimate-with-routes")]
        public string copyestimatewithroutes_ID
        {
            get
            {
                return ((string)(this["copyestimatewithroutes_ID"]));
            }
            set
            {
                this["copyestimatewithroutes_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("allowAnyShipTo")]
        public string allowAnyShipTo_ID
        {
            get
            {
                return ((string)(this["allowAnyShipTo_ID"]));
            }
            set
            {
                this["allowAnyShipTo_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("create-estimate")]
        public string createestimatebutton_ID
        {
            get
            {
                return ((string)(this["createestimatebutton_ID"]));
            }
            set
            {
                this["createestimatebutton_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#price-saved-message > div.modal-dialog > div.modal-content > div.modal-body")]
        public string Approvetest_CSS
        {
            get
            {
                return ((string)(this["Approvetest_CSS"]));
            }
            set
            {
                this["Approvetest_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("edit-estimate-form")]
        public string editestimateform_ID
        {
            get
            {
                return ((string)(this["editestimateform_ID"]));
            }
            set
            {
                this["editestimateform_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("createnewproduct-button")]
        public string createnewproduct_ID
        {
            get
            {
                return ((string)(this["createnewproduct_ID"]));
            }
            set
            {
                this["createnewproduct_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("filterByProductID")]
        public string filterByProduct_ID
        {
            get
            {
                return ((string)(this["filterByProduct_ID"]));
            }
            set
            {
                this["filterByProduct_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("search")]
        public string Estimatefilter_ID
        {
            get
            {
                return ((string)(this["Estimatefilter_ID"]));
            }
            set
            {
                this["Estimatefilter_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div#divMain > div#gbox_list > div#gview_list > div.ui-jqgrid-bdiv > div > table#l" +
            "ist > tbody > tr:nth-child(2) > td:nth-child(3) > a.estimate-screen-link.underli" +
            "ne")]
        public string SpecFilterTable_CSS
        {
            get
            {
                return ((string)(this["SpecFilterTable_CSS"]));
            }
            set
            {
                this["SpecFilterTable_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"estimate-price-table\"]/tbody/tr[14]/td[2]")]
        public string EstimateTable_XPATH
        {
            get
            {
                return ((string)(this["EstimateTable_XPATH"]));
            }
            set
            {
                this["EstimateTable_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaterialID")]
        public string Bundlestrappingmaterial_ID
        {
            get
            {
                return ((string)(this["Bundlestrappingmaterial_ID"]));
            }
            set
            {
                this["Bundlestrappingmaterial_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("copy-estimate-with-routes")]
        public string CopyExsistingEstimate_ID
        {
            get
            {
                return ((string)(this["CopyExsistingEstimate_ID"]));
            }
            set
            {
                this["CopyExsistingEstimate_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IB")]
        public string NumberPerBundle_ID
        {
            get
            {
                return ((string)(this["NumberPerBundle_ID"]));
            }
            set
            {
                this["NumberPerBundle_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pricing-grid-container")]
        public string Estimategrid_ID
        {
            get
            {
                return ((string)(this["Estimategrid_ID"]));
            }
            set
            {
                this["Estimategrid_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("productKit")]
        public string AssembledProductKit_ID
        {
            get
            {
                return ((string)(this["AssembledProductKit_ID"]));
            }
            set
            {
                this["AssembledProductKit_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add_productKit")]
        public string addproductKit_ID
        {
            get
            {
                return ((string)(this["addproductKit_ID"]));
            }
            set
            {
                this["addproductKit_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChildProductSpecID")]
        public string ChildProductSpec_ID
        {
            get
            {
                return ((string)(this["ChildProductSpec_ID"]));
            }
            set
            {
                this["ChildProductSpec_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tr#tr_ChildProductSpecID > td.DataTD > div.ui-autocomplete-pagination-results > u" +
            "l.ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.ui-corner-all > l" +
            "i.ui-menu-item")]
        public string ChildSpec_CSS
        {
            get
            {
                return ((string)(this["ChildSpec_CSS"]));
            }
            set
            {
                this["ChildSpec_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostPercentage")]
        public string CostPercentage_ID
        {
            get
            {
                return ((string)(this["CostPercentage_ID"]));
            }
            set
            {
                this["CostPercentage_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumberIn")]
        public string PartMultiplier_ID
        {
            get
            {
                return ((string)(this["PartMultiplier_ID"]));
            }
            set
            {
                this["PartMultiplier_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tr#Act_Buttons > td.EditButton > a#sData")]
        public string SubmitChildPart_CSS
        {
            get
            {
                return ((string)(this["SubmitChildPart_CSS"]));
            }
            set
            {
                this["SubmitChildPart_CSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" //div[starts-with(@id, \'pEstimateRoute\')]/input[2]")]
        public string AssembleSplit_XPATH
        {
            get
            {
                return ((string)(this["AssembleSplit_XPATH"]));
            }
            set
            {
                this["AssembleSplit_XPATH"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btnIsNewRevision")]
        public string RevisionProduct_ID
        {
            get
            {
                return ((string)(this["RevisionProduct_ID"]));
            }
            set
            {
                this["RevisionProduct_ID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumberOut")]
        public string PartDivider_ID
        {
            get
            {
                return ((string)(this["PartDivider_ID"]));
            }
            set
            {
                this["PartDivider_ID"] = value;
            }
        }
    }
}
